### ISSUE TITLE
Extract also data as ex-medio-sklik does

### ISSUE THREAD

**Issue by odinuv** [keboola/sklik-extractor#11]
1) hlavní rozdíl je v tom, že náš extraktor tahá nejenom data o kampaních, ale i reklamních sestavách (větší granularita) než Keboolí extraktor.
https://keboola.zendesk.com/agent/tickets/8434

**Comment by odinuv** [comment]
cili https://api.sklik.cz/cipisek/groups.get.html a https://api.sklik.cz/cipisek/groups.stats.html ?
https://api.sklik.cz/drak/groups.stats.html ?

**Comment by JakubMatejka** [comment]
Nově se dají stáhnout data z jakýkoli resoursy podporující metody `createReport` a `readReport` přes API v. Drak.
