### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by odinuv** [keboola/sklik-extractor#15]
Application error: Application error: {"error":"BAD REQUEST","method":"patterns.readReport","args":[{"session":"--omitted--"},"bc6Z;erFTdUVXW)75ed2be",{"offset":11 ... ame","clicks","impressions","clickMoney","id"]}],"statusCode":400,"response":{"status":400,"statusMessage":"Bad arguments!"}}

ExceptionId docker-85fef85a5a2a4e7e932d94d8a8d6d741 

Should this be some readable user error?

**Comment by JakubMatejka** [comment]
WTF? Ta chyba vznikla tady: https://github.com/keboola/sklik-extractor/blob/master/src/SklikApi.php#L217 a rozhodně je to `Keboola\SklikExtractor\Exception` (už kvůli tomu formátu message). Jenže ta výjimka dědí z `Keboola\Component\UserException` a měla by  teda být odchycená tady: https://github.com/keboola/sklik-extractor/blob/master/src/run.php#L16 a exitnout s kódem `1`, ne?

**Comment by odinuv** [comment]
tyjo to je divny, ono to navic dobehlo uspesne https://papertrailapp.com/groups/23635/events?focus=971323971817578504&selected=971323971817578504
to bude mozna neco podobnyho jak tady https://github.com/keboola/ex-facebook-graph-api/issues/46
no asi bych na to ted prdel
