### ISSUE TITLE
Undefined index: batchCallLimits 

### ISSUE THREAD

**Issue by odinuv** [keboola/sklik-extractor#20]
"errorOutput": "[2018-11-07 04:11:17] CRITICAL: ErrorException:Undefined index: batchCallLimits {\"errFile\":\"\/code\/src\/SklikApi.php\",\"errLine\":56,\"errCode\":0,\"errTrace\":\"#0 \/code\/src\/SklikApi.php(56): Keboola\\\\Component\\\\BaseComponent::Keboola\\\\Component\\\\{closure}(8, 'Undefined index...', '\/code\/src\/Sklik...', 56, Array)\\n#1 \/code\/src\/Extractor.php(34): Keboola\\\\SklikExtractor\\\\SklikApi->getListLimit()\\n#2 \/code\/src\/Component.php(26): Keboola\\\\SklikExtractor\\\\Extractor->run(Object(Keboola\\\\SklikExtractor\\\\Config))\\n#3 \/code\/src\/run.php(14): Keboola\\\\SklikExtractor\\\\Component->run()\\n#4 {main}\",\"errPrevious\":\"\"} 

https://keboola.slack.com/archives/C09U3R1J4/p1541563929002900

**Comment by odinuv** [comment]
dneksa znovu https://keboola.slack.com/archives/C09U3R1J4/p1541823251011200

**Comment by tomasfejfar** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1554207968000600

**Comment by tomasfejfar** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1554208088000700

**Comment by tomasfejfar** [comment]
Dnes opět

**Comment by ErikZigo** [comment]
Dnes opět
