### ISSUE TITLE
Keboola\\Csv\\Exception:Cannot write data into column

### ISSUE THREAD

**Issue by ujovlado** [keboola/sklik-extractor#28]
```
Keboola\Csv\Exception:Cannot write data into column: array ( 'parentId' => NULL, 'name' => 'Pardubický', 'id' => 10007, ) {"errFile":"/code/vendor/keboola/csv/src/CsvWriter.php","errLine":117,"errCode":3,"errTrace":"#0 /code/vendor/keboola/csv/src/CsvWriter.php(82): Keboola\\Csv\\CsvWriter->rowToStr(Array)
#1 /code/src/UserStorage.php(66): Keboola\\Csv\\CsvWriter->writeRow(Array)
#2 /code/src/UserStorage.php(114): Keboola\\SklikExtractor\\UserStorage->save('campaigns', Array)
#3 /code/src/Extractor.php(82): Keboola\\SklikExtractor\\UserStorage->saveReport('campaigns', Array, 330209, 'id')
#4 /code/src/Component.php(32): Keboola\\SklikExtractor\\Extractor->run(Object(Keboola\\SklikExtractor\\Config))
#5 /code/vendor/keboola/php-component/src/BaseComponent.php(205): Keboola\\SklikExtractor\\Component->run()
#6 /code/src/run.php(14): Keboola\\Component\\BaseComponent->execute()
#7 {main}","errPrevious":""} []
```

`docker-79a04081339705eb7630100e4066e467`

**Comment by ujovlado** [comment]
Looks like there a problem with downloading `regions.id, regions.parentId, regions.name`. It works without these columns.

**Comment by JakubMatejka** [comment]
Takže oni chtějí stahovat report kampaní (http://api.sklik.cz/drak/campaigns.list.html) a když tam zadají `regions.*`, tak to failuje. Ale proč resp. kde? `CsvWriter` nedává ten `NULL`? Podle:
![image](https://user-images.githubusercontent.com/215660/60125089-598a6080-978b-11e9-8b04-8c2e6c64aaa3.png)
to vypadá, že nulová hodnota v `regions.parentId` je legální hodnota.

**Comment by ujovlado** [comment]
Jo, imho to nespracuje writer (vid. ta exception). Inac som isiel presne podla tej dokumentacie. Zda sa mi ale, ze mi o padalo aj ked som tam nechal len `region.id` a `region.name` -> mohlo by to byt teoreticky sposobene nejakym zlym kodovanim?

**Comment by ujovlado** [comment]
Pozeram este tenn kod writer:
https://github.com/keboola/php-csv/blob/aed833b49b116ab29efb200f2175c5b4009ab083/src/CsvWriter.php#L118

Nebude to teda tym, ze by nevedel zapisat NULL, skor to bude tym, ze tam prislo pole.

Preto mi to neficalo ani ked som odstranil `parentId`.

**Comment by JakubMatejka** [comment]
Jo, zrovna jsem na to ráno koukal a taky mi to došlo. Akorát nevím do kterýho sloupce. Hodila by se mi přesná konfigurace.

**Comment by ujovlado** [comment]
Fixed in #29
