### ISSUE TITLE
Pri vypadku API extraktor skonci timeoutom

### ISSUE THREAD

**Issue by MiroCillik** [keboola/sklik-extractor#3]
Mal by hodit nejaku zmysluplnu chybovu hlasku. Podrobnosti tu https://keboola.zendesk.com/agent/tickets/5705

**Comment by JakubMatejka** [comment]
Hm, to ale vyfailovalo na timeoutu docker runneru, ne? V API to nijak poznat nejde a nedovedu si moc představit jak bych to měl detekovat. Leda tak v asynchronním vlákně sledovat stopky a po určité(?) době to prohlásit za výpadek API. Takže v php zatím asi těžko ;o)

**Comment by MiroCillik** [comment]
To mas sice pravdu, ze to bol timeout dockeru, ale za normalnych okolnosti ten job bezi tak 5minut. Teraz bezal vyse hodiny. Nie je to sposobene nejakym backoffom? Ja som inak tej komponente zvysil timeout na 2 hodiny.

**Comment by JakubMatejka** [comment]
A jo, jasně. ;o) Splet jsem že, to má vlastní sdkčko. Je to nějaký to xml-rpc a myslel jsem, že tam prostě na dlouhou dobu vytuhlo spojení. Je to teda nad Zend http klientem a mám tam backoff a repeat, ale ten je deset opakování se sleepem po 10-30 vteřinách. Pokud nepomůže, tak se loguje app error, a to se nestalo v případě ani jednoho api callu. Takže to spíš vypadá, že ta odstávka nebyla úplná (že jim třeba bežel aspoň nějaký malý server, který zvládl jen pár requestů?) a ten backoff ji bezpečně pokryl. Jenže to pak sestřelil ten runner.
