### ISSUE TITLE
Undefined index: dateFrom

### ISSUE THREAD

**Issue by odinuv** [keboola/sklik-extractor#32]
https://keboola.slack.com/archives/C09U3R1J4/p1562072786034700

**Comment by odinuv** [comment]
Undefined index: dateTo 

ErrorException:Undefined index: dateTo {\"errFile\":\"\/code\/src\/Extractor.php\",\"errLine\":61,\"errCode\":0,\"errTrace\":\"#0 \/code\/src\/Extractor.php(61): Keboola\\\\Component\\\\BaseComponent::Keboola\\\\Component\\\\{closure}(8, 'Undefined index...', '\/code\/src\/Extra...', 61, Array)\\n#1 \/code\/src\/Component.php(32): Keboola\\\\SklikExtractor\\\\Extractor->run(Object(Keboola\\\\SklikExtractor\\\\Config))\\n#2 \/code\/vendor\/keboola\/php-component\/src\/BaseComponent.php(205): Keboola\\\\SklikExtractor\\\\Component->run()\\n#3 \/code\/src\/run.php(14): Keboola\\\\Component\\\\BaseComponent->execute()\\n#4 {main}\",\"errPrevious\":\"\"}

**Comment by odinuv** [comment]
problem je tady
https://github.com/keboola/sklik-extractor/blob/0a9f31d7ea95922918881916fce619ff73df9a8b/src/Extractor.php#L58

V dokumentaci je

> dateFrom and dateTo are required values. If omitted, yesterday's dates will be used.

coz se nezda, ze by byla pravda, tady https://github.com/keboola/sklik-extractor/blob/0a9f31d7ea95922918881916fce619ff73df9a8b/src/SklikApi.php#L157  je kontrola, ze je to povinny, ale ta se provede az za konverzi https://github.com/keboola/sklik-extractor/blob/0a9f31d7ea95922918881916fce619ff73df9a8b/src/Extractor.php#L58

**Comment by Halama** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1562412372038100
