### ISSUE TITLE
Argument 3 passed to createReport() must be of the type array or null, object given

### ISSUE THREAD

**Issue by odinuv** [keboola/sklik-extractor#34]
https://keboola.slack.com/archives/C09U3R1J4/p1565918267004200

TypeError:Argument 3 passed to Keboola\\SklikExtractor\\SklikApi::createReport() must be of the type array or null, object given, called in \/code\/src\/Extractor.php on line 72 {\"errFile\":\"\/code\/src\/SklikApi.php\",\"errLine\":148,\"errCode\":0,\"errTrace\":\"#0 \/code\/src\/Extractor.php(72): Keboola\\\\SklikExtractor\\\\SklikApi->createReport('campaigns', Array, Object(stdClass), 2114)\\n#1 \/code\/src\/Component.php(32): Keboola\\\\SklikExtractor\\\\Extractor->run(Object(Keboola\\\\SklikExtractor\\\\Config))\\n#2 \/code\/vendor\/keboola\/php-component\/src\/BaseComponent.php(205): Keboola\\\\SklikExtractor\\\\Component->run()\\n#3 \/code\/src\/run.php(14): Keboola\\\\Component\\\\BaseComponent->execute()\\n#4 {main}\

**Comment by JakubMatejka** [comment]
https://github.com/keboola/sklik-extractor/releases/tag/3.3.3
